
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webapp-service
spec:
  selector:
    app: {{ .Release.Name }}-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
